# Evaluation config matching the ACTUAL trained model from run hjnqclgk
# The model was trained with hidden_dim=64 (not 96 as originally intended)

data:
  task: burgers1d
  split: test
  root: data/pdebench
  patch_size: 1

latent:
  dim: 32
  tokens: 32

# ACTUAL architecture from trained checkpoints
operator:
  pdet:
    input_dim: 32
    hidden_dim: 96  # This one is correct
    depths: [1, 1, 1]
    group_size: 12
    num_heads: 6

diffusion:
  latent_dim: 32
  hidden_dim: 64  # ACTUAL value from checkpoint (not 96!)
  num_layers: 3
  time_embed_dim: 128
  dropout: 0.0

training:
  batch_size: 8
  num_workers: 0
  tau: 0.5

# TTC configuration
ttc:
  enabled: true
  steps: 3
  candidates: 16
  beam_width: 5
  horizon: 3
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 300
  
  sampler:
    tau_range: [0.15, 0.85]
    noise_std: 0.015
    noise_schedule: [0.03, 0.015, 0.005]
  
  reward:
    analytical_weight: 1.0
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []
    weights:
      mass: 2.0
      energy: 0.3
      penalty_negative: 1.0
    critic:
      weight: 0.0
      hidden_dim: 256
      dropout: 0.1
  
  decoder:
    latent_dim: 32
    query_dim: 2
    hidden_dim: 96  # Matches operator
    mlp_hidden_dim: 128
    num_layers: 3
    num_heads: 6
    frequencies: [1.0, 2.0, 4.0, 8.0]
    output_channels:
      rho: 1
      e: 1

