# Evaluation configuration for PDEBench Burgers1D val split.
include: defaults

data:
  task: burgers1d
  split: val
  root: data/pdebench
  patch_size: 1

latent:
  dim: 32
  tokens: 16

training:
  batch_size: 16
  dt: 0.1

operator:
  pdet:
    input_dim: 32
    hidden_dim: 64
    depths: [1, 1, 1]
    group_size: 16
    num_heads: 4

logging:
  wandb:
    enabled: true
    project: universal-simulator
    run_name: burgers1d-eval-val
