include: defaults

data:
  task: burgers1d
  split: train
  root: data/pdebench
  patch_size: 1

latent:
  dim: 32
  tokens: 16

baseline:
  epochs: 5
  patience: 2
  log_path: reports/baseline_log.jsonl

optimizer:
  lr: 1.0e-3
  weight_decay: 0.0

scheduler:
  name: steplr
  step_size: 2
  gamma: 0.5

checkpoint:
  dir: checkpoints/

logging:
  wandb:
    enabled: true
    project: universal-simulator
    run_name: burgers1d-baseline
    group: burgers1d
