include: train_burgers_quality_v2.yaml

# 8-dim ultra-small model with pru2jxc4 training + TTC
# 
# Testing hypothesis: Does even smaller baseline give TTC even more room to optimize?
# 
# Expected:
#   Baseline: 0.95+ NRMSE (very poor)
#   TTC: 0.12-0.15 NRMSE (TTC can't fully compensate for lack of capacity)
# 
# This tests the lower bound of capacity for TTC effectiveness

data:
  task: burgers1d
  split: train
  root: data/pdebench
  patch_size: 1
  download:
    test_val_datasets: burgers1d_full_v1
    train_files:
      - source: full/burgers1d/burgers1d_train_000.h5
        symlink: burgers1d_train.h5

latent:
  dim: 8         # Ultra-small
  tokens: 8      # Scale proportionally

training:
  time_stride: 2
  batch_size: 16  # Can use higher batch with tiny model
  
  # pru2jxc4 settings
  num_workers: 8
  use_parallel_encoding: true
  
  latent_cache_dir: data/latent_cache
  checkpoint_interval: 50
  
  distill_micro_batch: 3
  distill_num_taus: 5
  
  compile: true
  pin_memory: true
  
  tau_distribution:
    type: beta
    alpha: 1.2
    beta: 1.2

operator:
  pdet:
    input_dim: 8       # Match latent dim
    hidden_dim: 16     # 2× latent dim
    depths: [1, 1, 1]
    group_size: 4      # Divides 16 evenly
    num_heads: 2       # Reduced for small model

diffusion:
  latent_dim: 8
  hidden_dim: 16

stages:
  operator:
    epochs: 15  # Match pru2jxc4
    
    optimizer:
      name: adamw
      lr: 1.0e-3            # CONSTANT LR
      weight_decay: 0.02

  diff_residual:
    epochs: 5
    grad_clip: 1.0
    ema_decay: 0.999
    
    optimizer:
      name: adamw
      lr: 3.0e-5
      weight_decay: 0.01
      betas: [0.9, 0.999]
    
    scheduler:
      name: cosineannealinglr
      t_max: 5
      eta_min: 3.0e-6

  consistency_distill:
    epochs: 6
    batch_size: 6
    
    optimizer:
      name: adamw
      lr: 2.0e-5
      weight_decay: 0.01
      betas: [0.9, 0.999]
    
    scheduler:
      name: cosineannealinglr
      t_max: 6
      eta_min: 2.0e-6

evaluation:
  enabled: true

ttc:
  enabled: true
  steps: 1
  candidates: 6
  beam_width: 2
  horizon: 2
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 100
  sampler:
    tau_range: [0.2, 0.8]
    noise_std: 0.01
    noise_schedule: [0.02, 0.01]
  reward:
    analytical_weight: 1.0
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []
    weights:
      mass: 1.0
      energy: 0.1
      penalty_negative: 0.5
    critic:
      weight: 0.0
      hidden_dim: 256
      dropout: 0.1
  decoder:
    latent_dim: 8
    query_dim: 2
    hidden_dim: 16
    mlp_hidden_dim: 16
    num_layers: 2
    num_heads: 2
    frequencies: [1.0, 2.0, 4.0]
    output_channels:
      rho: 1
      e: 1

logging:
  wandb:
    enabled: true
    project: universal-simulator
    entity: emgun-morpheus-space
    run_name: burgers8-pru2jxc4-phase1
    tags: [8dim, pru2jxc4_config, phase1_mapping, ultra_small]

# Expected: Capacity floor test
# Training time: ~10 min on H200
# Cost: ~$0.35 @ $2.11/hr

