include: train_burgers_quality_v2.yaml

# 16-dim optimal candidate with pru2jxc4 training + TTC
# 
# Hypothesis: Sweet spot for TTC effectiveness
# 
# Expected:
#   Baseline: 0.90 NRMSE (poor but not terrible)
#   TTC: 0.07-0.10 NRMSE (excellent!)
#   Improvement: ~90%
# 
# If successful, this becomes the optimal deployment model:
#   - 2× smaller than 32-dim
#   - Better performance than 32-dim + TTC (0.09)
#   - Ultra-efficient (30KB checkpoint)

data:
  task: burgers1d
  split: train
  root: data/pdebench
  patch_size: 1
  download:
    test_val_datasets: burgers1d_full_v1
    train_files:
      - source: full/burgers1d/burgers1d_train_000.h5
        symlink: burgers1d_train.h5

latent:
  dim: 16        # Half of 32-dim
  tokens: 16     # Scale proportionally

training:
  time_stride: 2
  batch_size: 14  # Between 32-dim (12) and 8-dim (16)
  
  # pru2jxc4 settings
  num_workers: 8
  use_parallel_encoding: true
  
  latent_cache_dir: data/latent_cache
  checkpoint_interval: 50
  
  distill_micro_batch: 3
  distill_num_taus: 5
  
  compile: true
  pin_memory: true
  
  tau_distribution:
    type: beta
    alpha: 1.2
    beta: 1.2

operator:
  pdet:
    input_dim: 16      # Match latent dim
    hidden_dim: 32     # 2× latent dim
    depths: [1, 1, 1]
    group_size: 8      # Divides 32 evenly
    num_heads: 4

diffusion:
  latent_dim: 16
  hidden_dim: 32

stages:
  operator:
    epochs: 15  # Match pru2jxc4 (constant LR is key)
    
    optimizer:
      name: adamw
      lr: 1.0e-3            # CONSTANT LR
      weight_decay: 0.02
    
    # NO SCHEDULER = constant LR

  diff_residual:
    epochs: 5
    grad_clip: 1.0
    ema_decay: 0.999
    
    optimizer:
      name: adamw
      lr: 3.0e-5
      weight_decay: 0.01
      betas: [0.9, 0.999]
    
    scheduler:
      name: cosineannealinglr
      t_max: 5
      eta_min: 3.0e-6

  consistency_distill:
    epochs: 6
    batch_size: 6
    
    optimizer:
      name: adamw
      lr: 2.0e-5
      weight_decay: 0.01
      betas: [0.9, 0.999]
    
    scheduler:
      name: cosineannealinglr
      t_max: 6
      eta_min: 2.0e-6

evaluation:
  enabled: true  # Auto-run evaluation after training

ttc:
  enabled: true
  steps: 1
  candidates: 6
  beam_width: 2
  horizon: 2
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 100
  sampler:
    tau_range: [0.2, 0.8]
    noise_std: 0.01
    noise_schedule: [0.02, 0.01]
  reward:
    analytical_weight: 1.0
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []
    weights:
      mass: 1.0
      energy: 0.1
      penalty_negative: 0.5
    critic:
      weight: 0.0
      hidden_dim: 256
      dropout: 0.1
  decoder:
    latent_dim: 16
    query_dim: 2
    hidden_dim: 32
    mlp_hidden_dim: 32
    num_layers: 2
    num_heads: 4
    frequencies: [1.0, 2.0, 4.0]
    output_channels:
      rho: 1
      e: 1

logging:
  wandb:
    enabled: true
    project: universal-simulator
    entity: emgun-morpheus-space
    run_name: burgers16-pru2jxc4-phase1
    tags: [16dim, pru2jxc4_config, phase1_mapping, optimal_candidate, unified_pipeline]

# EXPECTED OUTCOMES:
# ─────────────────────────────────────────────────────────────────────────────
#
# Baseline (no TTC):
#   NRMSE: 0.90 (worse than 32-dim's 0.78, better than expected 8-dim's 0.95+)
#
# With TTC:
#   NRMSE: 0.07-0.10 (BETTER than 32-dim's 0.09!)
#   
# If this achieves 0.07-0.08 NRMSE:
#   → 16-dim is the TRUE optimal dimension
#   → 2× smaller than 32-dim
#   → Better performance
#   → Perfect for production deployment
#   → Groundbreaking finding for publication!
#
# ─────────────────────────────────────────────────────────────────────────────
# Training time: ~15 min on H200
# Cost: ~$0.50 @ $2.11/hr
#
# Model size comparison:
#   8-dim:   ~30KB checkpoint (too small?)
#   16-dim:  ~60KB checkpoint (this config - optimal?)
#   32-dim:  ~120KB checkpoint (current winner: 0.09 NRMSE)
#   64-dim:  ~480KB checkpoint (worse: 0.11 NRMSE)

