# Ablation: 64 tokens
# Purpose: Find optimal token count for Burgers

seed: 42
deterministic: false
benchmark: true

data:
  task: burgers1d
  split: train
  root: data/pdebench
  patch_size: 1
  download:
    test_val_datasets: burgers1d_full_v1
    train_files:
      - source: full/burgers1d/burgers1d_train_000.h5
        symlink: burgers1d_train.h5

latent:
  dim: 64
  tokens: 64

operator:
  pdet:
    input_dim: 64
    hidden_dim: 128
    depths: [2, 2, 2]
    group_size: 16
    num_heads: 4

diffusion:
  latent_dim: 64
  hidden_dim: 128

training:
  batch_size: 8
  time_stride: 2
  dt: 0.1
  patience: 10

  num_workers: 4
  use_parallel_encoding: true
  pin_memory: true
  prefetch_factor: 2

  checkpoint_interval: 50

  amp: true
  compile: false
  grad_clip: 1.0
  ema_decay: 0.999
  accum_steps: 6

  # UPT Inverse Losses
  lambda_inv_enc: 0.5
  lambda_inv_dec: 0.5
  use_inverse_losses: true
  inverse_loss_frequency: 10

  lambda_spectral: 0.05
  lambda_relative: 0.0

stages:
  operator:
    epochs: 25

    optimizer:
      name: adamw
      lr: 6.0e-4
      betas: [0.9, 0.999]
      weight_decay: 0.03

  diff_residual:
    epochs: 8

  consistency_distill:
    epochs: 8

checkpoint:
  dir: checkpoints

evaluation:
  enabled: true
  split: test

ttc:
  enabled: true
  steps: 1
  candidates: 8
  beam_width: 3
  horizon: 1
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 150

  sampler:
    tau_range: [0.15, 0.85]
    noise_std: 0.05
    noise_schedule: [0.08, 0.05, 0.02]

  reward:
    analytical_weight: 1.0
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []

    weights:
      mass: 1.0
      energy: 1.0
      penalty_negative: 0.5

    critic:
      weight: 0.0
      hidden_dim: 128
      dropout: 0.1

  decoder:
    latent_dim: 64
    query_dim: 2
    hidden_dim: 128
    mlp_hidden_dim: 128
    num_layers: 3

logging:
  wandb:
    enabled: true
    project: universal-simulator
    entity: emgun-morpheus-space
    run_name: burgers-ablation-64tokens
    tags: [ablation, 64tokens, 64dim, phase2]
    group: upt-ablation

