# Ablation: 64 tokens (FIXED + MUON + OPTIMIZED)
# Purpose: Fixed configuration for UPT Phase 2 with Muon optimizer and speed optimizations
# Changes from original:
#   - Optimizer: AdamW → Muon hybrid (2-3x faster convergence expected)
#   - Gradient clipping: 1.0 (re-enabled for inverse loss stability)
#   - Inverse loss weights: 0.5 → 0.01 (50x reduction)
#   - Inverse loss frequency: 10 → 1 (every iteration)
#   - Warmup epochs: 15 → 5 (faster ramp-up)
#   - Total epochs: 25 → 40 (more time for inverse loss training)
#   - Batch size: 8 → 12 (better gradient stability)
#   - Accum steps: 6 → 4 (maintain reasonable effective batch)
#   - Learning rate: 6e-4 → 1e-3 (scaled with model size)
#
# Speed Optimizations (NEW):
#   - Muon optimizer: Falls back to torch.optim.Muon (flash-muon requires manual install)
#   - torch.compile: reduce-overhead mode for balanced optimization (~10-15% speedup)
#   - num_workers: 4 → 8 for better data pipeline parallelism (~3-5% speedup)
#   - prefetch_factor: 2 → 4 for better GPU utilization
#
# Expected speedup: 1.15-1.2x total training time vs baseline (without flash-muon)
# Note: max-autotune incompatible with CUDA graphs due to tensor mutation in time_embed

seed: 42
deterministic: false
benchmark: true

data:
  task: burgers1d
  split: train
  root: data/pdebench
  patch_size: 1
  download:
    test_val_datasets: burgers1d_full_v1
    train_files:
      - source: full/burgers1d/burgers1d_train_000.h5
        symlink: burgers1d_train.h5

latent:
  dim: 64
  tokens: 64

operator:
  pdet:
    input_dim: 64
    hidden_dim: 128
    depths: [2, 2, 2]
    group_size: 16
    num_heads: 4

diffusion:
  latent_dim: 64
  hidden_dim: 128

training:
  batch_size: 12  # Increased from 8
  time_stride: 2
  dt: 0.1
  patience: 5    # Stop early if no improvement (was 15, too high)

  num_workers: 8  # OPTIMIZED: Increased from 4 for better data pipeline
  use_parallel_encoding: true
  pin_memory: true
  prefetch_factor: 4  # OPTIMIZED: Increased from 2 for better prefetching

  checkpoint_interval: 50

  amp: true
  compile: true  # OPTIMIZED: Enabled with reduce-overhead mode
  compile_mode: reduce-overhead  # OPTIMIZED: Balanced torch.compile (max-autotune incompatible with CUDA graphs)
  grad_clip: 1.0  # Re-enabled: Prevent gradient explosion with inverse losses
  ema_decay: 0.999
  accum_steps: 4  # Reduced from 6

  # UPT Inverse Losses (FIXED)
  lambda_inv_enc: 0.01  # Reduced from 0.5 (50x reduction)
  lambda_inv_dec: 0.01  # Reduced from 0.5 (50x reduction)
  use_inverse_losses: true
  inverse_loss_frequency: 1  # Every iteration (was 10)
  inverse_loss_warmup_epochs: 5  # Faster warmup (was implicit 15)
  inverse_loss_max_weight: 0.05  # Explicit cap

  lambda_spectral: 0.05
  lambda_relative: 0.0

stages:
  operator:
    epochs: 40  # Increased from 25 for proper inverse loss training

    optimizer:
      name: muon_hybrid  # CHANGED: Use Muon+AdamW hybrid
      lr: 1.0e-3  # Same LR as AdamW baseline
      weight_decay: 0.03

      # Muon-specific parameters (for 2D+ matrix params)
      muon_momentum: 0.95    # Nesterov momentum
      muon_ns_steps: 5       # Newton-Schulz iterations
      muon_backend: auto     # auto, flash, or torch

      # AdamW-specific parameters (for 1D vector params)
      betas: [0.9, 0.999]
      eps: 1.0e-8

  diff_residual:
    epochs: 0  # DISABLED: Skip diffusion for faster testing
    patience: 5  # Early stopping if validation doesn't improve

    optimizer:
      name: muon_hybrid
      lr: 3.0e-4  # 3.3x lower than operator
      weight_decay: 0.01
      muon_momentum: 0.95
      muon_ns_steps: 5
      muon_backend: auto
      betas: [0.9, 0.999]
      eps: 1.0e-8

    scheduler:
      name: ReduceLROnPlateau
      mode: min
      factor: 0.5  # Halve LR when loss plateaus
      patience: 3  # Wait 3 epochs before reducing
      min_lr: 1.0e-5  # Don't go below this

  consistency_distill:
    epochs: 0  # DISABLED: Skip consistency for faster testing
    patience: 5  # Early stopping if validation doesn't improve

    optimizer:
      name: muon_hybrid
      lr: 3.0e-4  # Same as diffusion
      weight_decay: 0.01
      muon_momentum: 0.95
      muon_ns_steps: 5
      muon_backend: auto
      betas: [0.9, 0.999]
      eps: 1.0e-8

    scheduler:
      name: CosineAnnealingLR
      t_max: 10  # Match max epochs
      eta_min: 1.0e-5  # Minimum LR at end

checkpoint:
  dir: checkpoints

evaluation:
  enabled: true
  split: test

ttc:
  enabled: true
  debug: true
  steps: 1  # Oct 15 setting (was 3)
  candidates: 6  # Oct 15 setting (was 8)
  beam_width: 2  # Oct 15 setting (was 3)
  horizon: 2
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 100  # Oct 15 setting (was 150)

  sampler:
    tau_range: [0.2, 0.8]  # Oct 15 setting (was [0.05, 0.95])
    noise_std: 0.01  # Oct 15 setting (was 0.12) - much less noise!
    noise_schedule: [0.02, 0.01]  # Oct 15 setting

  reward:
    analytical_weight: 1.0
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []

    weights:
      # Oct 15 settings - conservation penalties
      mass: 1.0  # Oct 15 setting (was 0.0)
      energy: 0.1  # Oct 15 setting (was 0.0)
      penalty_negative: 0.5  # Oct 15 setting (was 0.0)
      smoothness: 0.0  # Oct 15 setting (was 1.0)

    critic:
      weight: 0.0
      hidden_dim: 128
      dropout: 0.1

  decoder:
    latent_dim: 64
    query_dim: 2
    hidden_dim: 128
    mlp_hidden_dim: 128
    num_layers: 3
    num_heads: 4
    frequencies: [1.0, 2.0, 4.0, 8.0]
    output_channels:
      rho: 1
      e: 1

logging:
  wandb:
    enabled: true
    project: universal-simulator
    entity: emgun-morpheus-space
    run_name: burgers-ablation-64tokens-muon
    tags: [ablation, 64tokens, 64dim, phase2, fixed, inverse-losses-fixed, muon, muon-hybrid]
    group: upt-ablation-muon