# Quick evaluation test config
seed: 17

data:
  task: burgers1d
  split: test
  root: data/pdebench
  patch_size: 1

latent:
  dim: 128
  tokens: 64

operator:
  pdet:
    input_dim: 128
    hidden_dim: 256
    depths: [1, 1, 1]
    group_size: 64
    num_heads: 4

diffusion:
  hidden_dim: 256

eval:
  rollout_steps: 10  # Short rollout for quick test
  num_samples: 5     # Only evaluate 5 samples

checkpoint:
  operator: checkpoints/test/operator.pt
  diffusion: checkpoints/test/diffusion_residual.pt

logging:
  wandb:
    enabled: false

