# Baseline 512-dim Burgers1D evaluation (NO TTC) - TEST split
# Use this to measure improvement from TTC

seed: 17
precision: bf16

data:
  task: burgers1d
  split: test
  root: data/pdebench
  patch_size: 1

latent:
  dim: 512
  tokens: 128

training:
  batch_size: 32
  dt: 0.1
  num_workers: 0
  pin_memory: false

operator:
  pdet:
    input_dim: 512
    hidden_dim: 1024
    depths: [1, 1, 1]
    group_size: 256
    num_heads: 4

# NO TTC - baseline evaluation
ttc:
  enabled: false

logging:
  backend: stdout
  level: INFO
  wandb:
    enabled: true
    project: universal-simulator
    run_name: baseline-burgers512-test-notttc
    group: baseline-eval
    job_type: evaluation
    tags: [baseline, burgers1d, 512dim, test, no-ttc, sota-comparison]
