# Standalone 512-dim Burgers1D TTC evaluation config (validation split)
# No includes - all settings explicit for remote compatibility

seed: 17
precision: bf16

data:
  task: burgers1d
  split: val
  root: data/pdebench
  patch_size: 1

latent:
  dim: 512
  tokens: 128

training:
  batch_size: 32
  dt: 0.1
  num_workers: 0
  pin_memory: false

operator:
  pdet:
    input_dim: 512
    hidden_dim: 1024
    depths: [1, 1, 1]
    group_size: 256
    num_heads: 4

# TTC (Test-Time Computation) settings
ttc:
  enabled: true
  steps: 1
  candidates: 6
  beam_width: 2
  horizon: 2
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 100
  sampler:
    tau_range: [0.2, 0.8]
    noise_std: 0.01
  reward:
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []
    weights:
      mass: 1.0
      energy: 0.1
      penalty_negative: 0.5
  decoder:
    latent_dim: 512
    query_dim: 2
    hidden_dim: 256
    mlp_hidden_dim: 256
    num_layers: 2
    num_heads: 4
    frequencies: [1.0, 2.0, 4.0]
    output_channels:
      rho: 1
      e: 1

logging:
  backend: stdout
  level: INFO
  wandb:
    enabled: true
    project: universal-simulator
    run_name: ttc-eval-burgers512-val
    group: ttc-eval
    job_type: evaluation
    tags: [ttc, burgers1d, 512dim, validation]
