# Scale-ready evaluation config for PDEBench Burgers1D test split.
include: defaults

data:
  task: burgers1d
  split: test
  root: data/pdebench
  patch_size: 1

latent:
  dim: 128
  tokens: 64

training:
  batch_size: 32
  dt: 0.1

operator:
  pdet:
    input_dim: 128
    hidden_dim: 256
    depths: [1, 1, 1]
    group_size: 64
    num_heads: 4

logging:
  wandb:
    enabled: true
    project: universal-simulator
    run_name: burgers1d-eval-scale-test
    group: burgers1d-scale
    job_type: evaluation
