# Scale-ready evaluation config for PDEBench Burgers1D (val/test splits).
include: defaults

data:
  task: burgers1d
  split: val
  root: ${oc.env:PDEBENCH_ROOT,data/pdebench}
  patch_size: 1

latent:
  dim: 128
  tokens: 64

training:
  batch_size: 32
  dt: 0.1

operator:
  pdet:
    input_dim: 128
    hidden_dim: 256
    depths: [2, 2, 2]
    group_size: 32
    num_heads: 8

logging:
  wandb:
    enabled: true
    project: universal-simulator
    run_name: burgers1d-eval-scale-${data.split}
    group: burgers1d-scale
    job_type: evaluation
