run:
  mode: transient
  steps: 10
  dt: 0.1
  correct_every: 2
  corrector_tau: 0.5
  residual_threshold: 0.35
operator:
  latent_dim: 32
  pdet:
    input_dim: 32
    hidden_dim: 64
    depths: [1, 1, 1]
    group_size: 8
    num_heads: 2
models:
  operator_checkpoint: checkpoints/op_latest.ckpt
  corrector_checkpoint: checkpoints/corrector.ckpt
outputs:
  save_dir: export/transient/
  save_states: true
