include: train_burgers_32dim.yaml

# Lightweight overrides for 10–60 min proxy evals
data:
  split: valid

latent:
  tokens: 32          # Match training config (was 16, caused eval errors)

training:
  batch_size: 8
  time_stride: 4      # subsample temporal steps
  num_workers: 2
  prefetch_factor: 2

ttc:
  enabled: true
  steps: 1
  candidates: 4
  beam_width: 1
  horizon: 1
  max_evaluations: 30
  sampler:
    noise_std: 0.01
    noise_schedule: [0.02]

