# Round B: Capacity Scale-Up
# Variation: Increased latent capacity (32→48 tokens, 64→96 hidden)
# Hypothesis: More capacity will capture finer dynamics, reduce nRMSE

include: train_burgers_32dim.yaml

# ============================================================================
# LATENT SPACE - INCREASED CAPACITY
# ============================================================================
latent:
  dim: 32
  tokens: 32  # DOUBLED from 16 (more information capacity)

# ============================================================================
# OPERATOR ARCHITECTURE - WIDER NETWORK
# ============================================================================
operator:
  pdet:
    input_dim: 32
    hidden_dim: 96  # Increased from 64
    depths: [1, 1, 1]
    group_size: 12  # Scaled with hidden_dim
    num_heads: 6    # Scaled with hidden_dim

# ============================================================================
# DIFFUSION ARCHITECTURE - WIDER
# ============================================================================
diffusion:
  latent_dim: 32
  hidden_dim: 96  # Increased from 64

# ============================================================================
# TRAINING CONFIGURATION
# ============================================================================
training:
  batch_size: 10  # Reduced slightly for VRAM (larger model)
  time_stride: 2
  dt: 0.1
  patience: 10
  num_workers: 8
  use_parallel_encoding: true
  pin_memory: true
  prefetch_factor: 2
  latent_cache_dir: data/latent_cache
  latent_cache_dtype: float32
  checkpoint_interval: 50
  amp: true
  compile: true
  grad_clip: 1.0
  ema_decay: 0.9995
  accum_steps: 5  # Increased to maintain effective batch size

  distill_micro_batch: 2  # Reduced for VRAM
  distill_num_taus: 5

  lambda_spectral: 0.05
  lambda_relative: 0.0

  tau_distribution:
    type: beta
    alpha: 1.2
    beta: 1.2

# ============================================================================
# TRAINING STAGES - Scaled LR for larger model
# ============================================================================
stages:
  operator:
    epochs: 20

    optimizer:
      name: adamw
      lr: 4.0e-4  # Slightly higher for larger capacity
      betas: [0.9, 0.95]

    scheduler:
      name: cosineannealinglr
      t_max: 20
      eta_min: 1.0e-5
      warmup_steps_ratio: 0.05

  diff_residual:
    epochs: 8

    optimizer:
      name: adamw
      lr: 3.0e-5
      weight_decay: 0.01
      betas: [0.9, 0.95]

    scheduler:
      name: cosineannealinglr
      t_max: 8
      eta_min: 3.0e-6

  consistency_distill:
    epochs: 8
    batch_size: 5  # Reduced for VRAM
    accum_steps: 2

    optimizer:
      name: adamw
      lr: 2.0e-5
      weight_decay: 0.01
      betas: [0.9, 0.95]

    scheduler:
      name: cosineannealinglr
      t_max: 8
      eta_min: 2.0e-6

  steady_prior:
    epochs: 0

# ============================================================================
# TTC - Adjusted for larger latent space
# ============================================================================
ttc:
  enabled: true
  steps: 1
  candidates: 8
  beam_width: 3
  horizon: 1
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 150

  sampler:
    tau_range: [0.15, 0.85]
    noise_std: 0.015
    noise_schedule: [0.03, 0.015, 0.005]

  reward:
    analytical_weight: 1.0
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []

    weights:
      mass: 1.2
      energy: 0.15
      penalty_negative: 0.6

    critic:
      weight: 0.0
      hidden_dim: 256
      dropout: 0.1

  decoder:
    latent_dim: 32
    query_dim: 2
    hidden_dim: 96      # Scaled up
    mlp_hidden_dim: 192  # Scaled up
    num_layers: 3
    num_heads: 6        # Scaled up
    frequencies: [1.0, 2.0, 4.0, 8.0]

    output_channels:
      rho: 1
      e: 1

# ============================================================================
# LOGGING
# ============================================================================
logging:
  wandb:
    enabled: true
    project: universal-simulator
    entity: emgun-morpheus-space
    run_name: sweep-b-capacity-up
    tags: [sweep-round-b, capacity-scale, tokens-32, hidden-96, model-scaling]
    group: sota-sweep-round-b
