# UPT Diagnostic - 5 Epochs
# Version: Fixed gradient explosion issue
# Purpose: Quick validation that gradient norms stay stable
# Expected runtime: ~5-7 minutes on A100

seed: 42
deterministic: false
benchmark: true

data:
  task: burgers1d
  split: train
  root: data/pdebench
  patch_size: 1
  download:
    test_val_datasets: burgers1d_full_v1
    train_files:
      - source: full/burgers1d/burgers1d_train_000.h5
        symlink: burgers1d_train.h5

latent:
  dim: 16
  tokens: 32

operator:
  pdet:
    input_dim: 16
    hidden_dim: 96
    depths: [1, 1, 1]
    group_size: 12
    num_heads: 6

diffusion:
  latent_dim: 16
  hidden_dim: 96

training:
  batch_size: 12
  time_stride: 2
  dt: 0.1
  patience: 10

  num_workers: 4
  use_parallel_encoding: true
  pin_memory: true
  prefetch_factor: 2

  latent_cache_dir: data/latent_cache

  checkpoint_interval: 50

  amp: true
  compile: false  # Disabled for faster diagnostic startup

  # FIX 1: AGGRESSIVE GRADIENT CLIPPING
  grad_clip: 0.3
  grad_clip_per_param: true

  ema_decay: 0.999
  accum_steps: 4

  # FIX 2: MUCH SMALLER INVERSE LOSS WEIGHTS
  lambda_inv_enc: 0.001
  lambda_inv_dec: 0.001

  # FIX 3: CURRICULUM LEARNING
  inverse_loss_warmup_epochs: 15
  inverse_loss_max_weight: 0.05

  use_inverse_losses: true
  inverse_loss_frequency: 10

  lambda_spectral: 0.05
  lambda_relative: 0.0

  distill_micro_batch: 3
  distill_num_taus: 5

  tau_distribution:
    type: beta
    alpha: 1.2
    beta: 1.2

stages:
  operator:
    epochs: 5  # Quick diagnostic

    optimizer:
      name: adamw
      lr: 1.0e-3
      betas: [0.9, 0.999]
      weight_decay: 0.03

  diff_residual:
    epochs: 0  # Skip for diagnostic

  consistency_distill:
    epochs: 0  # Skip for diagnostic

  steady_prior:
    epochs: 0  # Skip for diagnostic

ttc:
  enabled: false  # Skip for diagnostic

checkpoint:
  dir: checkpoints

evaluation:
  enabled: false  # Skip for diagnostic

logging:
  wandb:
    enabled: true
    project: universal-simulator
    entity: emgun-morpheus-space
    run_name: burgers-upt-diagnostic
    tags: [16dim, upt, inverse-losses, diagnostic, gradient-check]
    group: upt-experiments
