# Muon Smoke Test Configuration - 1 epoch for quick validation
# Based on train_burgers_muon.yaml

# ============================================================================
# REPRODUCIBILITY
# ============================================================================
seed: 42
deterministic: true
benchmark: false

# ============================================================================
# DATA CONFIGURATION
# ============================================================================
data:
  task: burgers1d
  split: train
  root: data/pdebench
  patch_size: 1

  download:
    test_val_datasets: burgers1d_full_v1
    train_files:
      - source: full/burgers1d/burgers1d_train_000.h5
        symlink: burgers1d_train.h5

# ============================================================================
# LATENT SPACE
# ============================================================================
latent:
  dim: 16
  tokens: 32

# ============================================================================
# OPERATOR ARCHITECTURE
# ============================================================================
operator:
  pdet:
    input_dim: 16
    hidden_dim: 96
    depths: [1, 1, 1]
    group_size: 12
    num_heads: 6

# ============================================================================
# DIFFUSION ARCHITECTURE
# ============================================================================
diffusion:
  latent_dim: 16
  hidden_dim: 96

# ============================================================================
# TRAINING CONFIGURATION
# ============================================================================
training:
  batch_size: 12
  time_stride: 2
  dt: 0.1
  patience: 10

  num_workers: 8
  use_parallel_encoding: true
  pin_memory: true
  prefetch_factor: 2

  latent_cache_dir: data/latent_cache
  latent_cache_dtype: float32
  checkpoint_interval: 50

  amp: true
  compile: true
  grad_clip: null
  ema_decay: 0.999
  accum_steps: 4

  distill_micro_batch: 3
  distill_num_taus: 5

  lambda_spectral: 0.05
  lambda_relative: 0.0

  tau_distribution:
    type: beta
    alpha: 1.2
    beta: 1.2

# ============================================================================
# TRAINING STAGES
# ============================================================================
stages:
  operator:
    epochs: 1  # SMOKE TEST: Just 1 epoch

    optimizer:
      name: muon_hybrid
      lr: 1.0e-3
      weight_decay: 0.03

      # Muon-specific parameters (for 2D+ matrix params)
      muon_momentum: 0.95
      muon_ns_steps: 5
      muon_backend: auto

      # AdamW-specific parameters (for 1D vector params)
      betas: [0.9, 0.999]
      eps: 1.0e-8

  diff_residual:
    epochs: 0  # Skip for smoke test

  consistency_distill:
    epochs: 0  # Skip for smoke test

  steady_prior:
    epochs: 0  # Skip for smoke test

# ============================================================================
# TEST-TIME CONDITIONING (TTC)
# ============================================================================
ttc:
  enabled: true
  steps: 1
  candidates: 16
  beam_width: 5
  horizon: 1
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 200

  sampler:
    tau_range: [0.15, 0.85]
    noise_std: 0.05
    noise_schedule: [0.08, 0.05, 0.02]

  reward:
    analytical_weight: 1.0
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []

    weights:
      mass: 1.0
      energy: 1.0
      penalty_negative: 0.5

    critic:
      weight: 0.0
      hidden_dim: 256
      dropout: 0.1

  decoder:
    latent_dim: 16
    query_dim: 2
    hidden_dim: 96
    mlp_hidden_dim: 128
    num_layers: 3
    num_heads: 4
    frequencies: [1.0, 2.0, 4.0, 8.0]

    output_channels:
      rho: 1
      e: 1

# ============================================================================
# CHECKPOINT CONFIGURATION
# ============================================================================
checkpoint:
  dir: checkpoints

# ============================================================================
# EVALUATION
# ============================================================================
evaluation:
  enabled: false  # Skip for smoke test

# ============================================================================
# LOGGING
# ============================================================================
logging:
  wandb:
    enabled: false  # Skip WandB for smoke test
    project: universal-simulator
    entity: emgun-morpheus-space
    run_name: burgers-muon-smoke
    tags: [muon, smoke-test]
