# 32-dim v3: Option 1+2 Combined - Aggressive TTC + Extended Training + Rollout
# Goal: Get NRMSE < 0.045
# Self-contained config to avoid inheritance issues

data:
  task: burgers1d
  split: train
  root: data/pdebench
  patch_size: 1
  shard_limit: null
  download:
    test_val_datasets: burgers1d_full_v1
    train_files:
      - source: full/burgers1d/burgers1d_train_000.h5
        symlink: burgers1d_train.h5

latent:
  dim: 32
  tokens: 32

training:
  batch_size: 12
  time_stride: 2
  dt: 0.1
  patience: 10
  
  # Data loading
  num_workers: 8
  use_parallel_encoding: true
  pin_memory: true
  prefetch_factor: 2
  
  # Caching
  latent_cache_dir: data/latent_cache
  latent_cache_dtype: float32
  checkpoint_interval: 50
  
  # Optimization
  amp: true
  compile: true
  grad_clip: 1.0
  ema_decay: 0.999
  accum_steps: 4
  
  # Distillation
  distill_micro_batch: 3
  distill_num_taus: 5
  
  # Regularization
  lambda_spectral: 0.05
  lambda_relative: 0.0
  
  # Rollout loss (NEW in v3)
  rollout_horizon: 3          # Multi-step prediction training
  lambda_rollout: 0.1         # Weight for rollout loss
  
  # Tau distribution
  tau_distribution:
    type: beta
    alpha: 1.2
    beta: 1.2

# OPERATOR ARCHITECTURE - Explicitly defined
operator:
  pdet:
    input_dim: 32          # Must match latent.dim
    hidden_dim: 96         # 1.5× capacity upgrade
    depths: [1, 1, 1]
    group_size: 12         # Divides hidden_dim evenly
    num_heads: 6           # More attention heads

# DIFFUSION ARCHITECTURE - Explicitly defined
diffusion:
  latent_dim: 32           # Must match latent.dim
  hidden_dim: 96           # MUST match operator.pdet.hidden_dim
  num_layers: 3
  time_embed_dim: 128
  dropout: 0.0

# TRAINING STAGES (Extended for v3)
stages:
  operator:
    epochs: 50                # ↑ from 25 (2× training for better convergence)
    
    optimizer:
      name: adamw
      lr: 1.0e-3              # Constant LR
      weight_decay: 0.03
      betas: [0.9, 0.999]

  diff_residual:
    epochs: 15                # ↑ from 8 (more diffusion training)
    grad_clip: 1.0
    ema_decay: 0.999
    
    optimizer:
      name: adamw
      lr: 5.0e-5
      weight_decay: 0.015
      betas: [0.9, 0.999]
    
    scheduler:
      name: cosineannealinglr
      t_max: 15
      eta_min: 3.0e-6

  consistency_distill:
    epochs: 10                # ↑ from 8
    batch_size: 6
    
    optimizer:
      name: adamw
      lr: 3.0e-5
      weight_decay: 0.015
      betas: [0.9, 0.999]
    
    scheduler:
      name: cosineannealinglr
      t_max: 10
      eta_min: 2.0e-6

# OVERRIDE: Aggressive TTC settings
ttc:
  enabled: true
  steps: 3                    # ↑ from 1 (multi-step refinement)
  candidates: 16              # ↑ from 8 (more diversity)
  beam_width: 5               # ↑ from 3 (keep more hypotheses)
  horizon: 3                  # ↑ from 2 (longer lookahead)
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 300        # ↑ from 150 (more optimization)
  
  sampler:
    tau_range: [0.15, 0.85]
    noise_std: 0.015
    noise_schedule: [0.03, 0.015, 0.005]
  
  reward:
    analytical_weight: 1.0
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []
    weights:
      mass: 2.0               # ↑ from 1.2 (stricter conservation)
      energy: 0.3             # ↑ from 0.15
      penalty_negative: 1.0   # ↑ from 0.6 (stronger penalties)
    critic:
      weight: 0.0
      hidden_dim: 256
      dropout: 0.1
  
  decoder:
    latent_dim: 32         # Must match latent.dim
    query_dim: 2
    hidden_dim: 96         # Must match operator.pdet.hidden_dim
    mlp_hidden_dim: 128
    num_layers: 3
    num_heads: 6
    frequencies: [1.0, 2.0, 4.0, 8.0]
    output_channels:
      rho: 1
      e: 1

# EVALUATION - Runs after training
evaluation:
  enabled: true
  split: test

logging:
  wandb:
    enabled: true
    project: universal-simulator
    entity: emgun-morpheus-space
    run_name: burgers32-v3-aggressive
    tags: [32dim, v3_aggressive, option1_2, extended_training, aggressive_ttc]

# EXPECTED:
# ─────────────────────────────────────────────────────────────────────────────
# Training time: ~70 min on H200
#   Operator: 50 epochs × ~2.5s = ~2 min after compilation
#   Diffusion: 15 epochs × ~7s = ~2 min
#   Consistency: 10 epochs × ~5 min = ~50 min
#   Evaluation: ~45-60 min (aggressive TTC is slower)
#
# Total: ~115 min, Cost: ~$5.10 @ $2.66/hr
#
# Expected NRMSE: 0.040-0.045
#   - Better operator from 2× epochs + rollout loss
#   - Aggressive TTC pushes inference optimization to the limit
# ─────────────────────────────────────────────────────────────────────────────

