# Burgers1D Training with UPT Inverse Losses - OPTIMIZED VERSION
# Full speed: UPT-aware cache + torch.compile enabled
# Requires: 800GB disk (500GB UPT cache + 200GB compile kernels + margin)
#
# Phase 1 - UPT Inverse Losses Implementation
# Reference: thoughts/shared/plans/2025-01-23-upt-inverse-losses-implementation.md

seed: 42
deterministic: false
benchmark: true

data:
  task: burgers1d
  split: train
  root: data/pdebench
  patch_size: 1
  download:
    test_val_datasets: burgers1d_full_v1
    train_files:
      - source: full/burgers1d/burgers1d_train_000.h5
        symlink: burgers1d_train.h5

latent:
  dim: 16
  tokens: 32

operator:
  pdet:
    input_dim: 16
    hidden_dim: 96
    depths: [1, 1, 1]
    group_size: 12
    num_heads: 6

diffusion:
  latent_dim: 16
  hidden_dim: 96

training:
  batch_size: 12
  time_stride: 2
  dt: 0.1
  patience: 10

  # ENABLE UPT-AWARE CACHING (stores latents + physical fields)
  num_workers: 4  # Parallel workers for speed
  use_parallel_encoding: true
  pin_memory: true
  prefetch_factor: 2

  # UPT-aware latent cache (with physical fields)
  latent_cache_dir: data/latent_cache  # Cache enabled

  checkpoint_interval: 50

  amp: true
  compile: true  # ENABLED - faster training
  grad_clip: 1.0
  ema_decay: 0.999
  accum_steps: 4

  # UPT Inverse Losses
  lambda_inv_enc: 0.5
  lambda_inv_dec: 0.5
  use_inverse_losses: true
  inverse_loss_frequency: 10

  lambda_spectral: 0.05
  lambda_relative: 0.0

  distill_micro_batch: 3
  distill_num_taus: 5

  tau_distribution:
    type: beta
    alpha: 1.2
    beta: 1.2

stages:
  operator:
    epochs: 25

    optimizer:
      name: adamw
      lr: 1.0e-3
      betas: [0.9, 0.999]
      weight_decay: 0.03

  diff_residual:
    epochs: 8
    grad_clip: 1.0
    ema_decay: 0.999

    optimizer:
      name: adamw
      lr: 5.0e-5
      weight_decay: 0.015
      betas: [0.9, 0.999]

    scheduler:
      name: cosineannealinglr
      t_max: 8
      eta_min: 3.0e-6

  consistency_distill:
    epochs: 8
    batch_size: 6
    tau_schedule: [5, 4, 3]
    accum_steps: 2

    optimizer:
      name: adamw
      lr: 3.0e-5
      weight_decay: 0.015
      betas: [0.9, 0.999]

    scheduler:
      name: cosineannealinglr
      t_max: 8
      eta_min: 2.0e-6

  steady_prior:
    epochs: 0

ttc:
  enabled: true
  steps: 1
  candidates: 16
  beam_width: 5
  horizon: 1
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 200

  sampler:
    tau_range: [0.15, 0.85]
    noise_std: 0.05
    noise_schedule: [0.08, 0.05, 0.02]

  reward:
    analytical_weight: 1.0
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []

    weights:
      mass: 1.0
      energy: 1.0
      penalty_negative: 0.5

    critic:
      weight: 0.0
      hidden_dim: 256
      dropout: 0.1

  decoder:
    latent_dim: 16
    query_dim: 2
    hidden_dim: 96
    mlp_hidden_dim: 128
    num_layers: 3
    num_heads: 4
    frequencies: [1.0, 2.0, 4.0, 8.0]

    output_channels:
      rho: 1
      e: 1

checkpoint:
  dir: checkpoints

evaluation:
  enabled: true
  split: test

logging:
  wandb:
    enabled: true
    project: universal-simulator
    entity: emgun-morpheus-space
    run_name: burgers-upt-optimized
    tags: [16dim, upt, inverse-losses, optimized, cache, compile, phase1]
    group: upt-experiments
