# Golden Burgers1D Training Configuration - NO DIFFUSION
# Test if diffusion stage is hurting performance (based on variance analysis)
#
# Changes from train_burgers_golden.yaml:
# - Diffusion epochs: 8 → 0 (DISABLED)
# - Consistency epochs: 8 → 0 (DISABLED, depends on diffusion)
# - Added reproducibility settings (seed=42, deterministic=true)
#
# Hypothesis: Diffusion overfitting may be causing eval variance and poor performance.
# The inverse correlation (-0.394) between diffusion loss and NRMSE suggests that
# when diffusion trains "well" (low loss), eval actually gets worse.

# ============================================================================
# REPRODUCIBILITY
# ============================================================================
seed: 42                    # Fixed random seed for reproducibility
deterministic: true         # Enable deterministic algorithms
benchmark: false            # Disable cudnn benchmarking for reproducibility

# ============================================================================
# DATA CONFIGURATION
# ============================================================================
data:
  task: burgers1d
  split: train
  root: data/pdebench
  patch_size: 1

  download:
    test_val_datasets: burgers1d_full_v1
    train_files:
      - source: full/burgers1d/burgers1d_train_000.h5
        symlink: burgers1d_train.h5

# ============================================================================
# LATENT SPACE
# ============================================================================
latent:
  dim: 16
  tokens: 32

# ============================================================================
# OPERATOR ARCHITECTURE
# ============================================================================
operator:
  pdet:
    input_dim: 16
    hidden_dim: 96
    depths: [1, 1, 1]
    group_size: 12
    num_heads: 6

# ============================================================================
# DIFFUSION ARCHITECTURE
# ============================================================================
diffusion:
  latent_dim: 16
  hidden_dim: 96

# ============================================================================
# TRAINING CONFIGURATION
# ============================================================================
training:
  batch_size: 12
  time_stride: 2
  dt: 0.1
  patience: 10

  num_workers: 8
  use_parallel_encoding: true
  pin_memory: true
  prefetch_factor: 2

  latent_cache_dir: data/latent_cache
  latent_cache_dtype: float32
  checkpoint_interval: 50

  amp: true
  compile: true
  grad_clip: 1.0
  ema_decay: 0.999
  accum_steps: 4

  distill_micro_batch: 3
  distill_num_taus: 5

  lambda_spectral: 0.05
  lambda_relative: 0.0

  tau_distribution:
    type: beta
    alpha: 1.2
    beta: 1.2

# ============================================================================
# TRAINING STAGES
# ============================================================================
stages:
  operator:
    epochs: 25

    optimizer:
      name: adamw
      lr: 1.0e-3
      betas: [0.9, 0.999]
      weight_decay: 0.03

  diff_residual:
    epochs: 0  # DISABLED - Test baseline without diffusion

  consistency_distill:
    epochs: 0  # DISABLED - Depends on diffusion

  steady_prior:
    epochs: 0

# ============================================================================
# TEST-TIME CONDITIONING (TTC)
# ============================================================================
ttc:
  enabled: true
  steps: 1
  candidates: 8
  beam_width: 3
  horizon: 1
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 150

  sampler:
    tau_range: [0.15, 0.85]
    noise_std: 0.015
    noise_schedule: [0.03, 0.015, 0.005]

  reward:
    analytical_weight: 1.0
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []

    weights:
      mass: 1.2
      energy: 0.15
      penalty_negative: 0.6

    critic:
      weight: 0.0
      hidden_dim: 256
      dropout: 0.1

  decoder:
    latent_dim: 16
    query_dim: 2
    hidden_dim: 96
    mlp_hidden_dim: 128
    num_layers: 3
    num_heads: 4
    frequencies: [1.0, 2.0, 4.0, 8.0]

    output_channels:
      rho: 1
      e: 1

# ============================================================================
# CHECKPOINT CONFIGURATION
# ============================================================================
checkpoint:
  dir: checkpoints

# ============================================================================
# EVALUATION
# ============================================================================
evaluation:
  enabled: true
  split: test

# ============================================================================
# LOGGING
# ============================================================================
logging:
  wandb:
    enabled: true
    project: universal-simulator
    entity: emgun-morpheus-space
    run_name: burgers-golden-no-diffusion
    tags: [16dim, golden, no-diffusion, reproducibility-test]
    group: diffusion-ablation
