# Burgers1D UPT Training - Operator Stage Only (Skip Consistency Distillation Bug)
# Version: 2.1 - Fixed gradient explosion + skip torch.compile() CUDA graph bug
#
# Based on train_burgers_upt_fixed.yaml but with consistency_distill.epochs = 0
# to avoid CUDA graph bug while still training operator and diffusion stages

seed: 42
deterministic: false
benchmark: true

data:
  task: burgers1d
  split: train
  root: data/pdebench
  patch_size: 1
  download:
    test_val_datasets: burgers1d_full_v1
    train_files:
      - source: full/burgers1d/burgers1d_train_000.h5
        symlink: burgers1d_train.h5

latent:
  dim: 16
  tokens: 32

operator:
  pdet:
    input_dim: 16
    hidden_dim: 96
    depths: [1, 1, 1]
    group_size: 12
    num_heads: 6

diffusion:
  latent_dim: 16
  hidden_dim: 96

training:
  batch_size: 12
  time_stride: 2
  dt: 0.1
  patience: 10

  num_workers: 4
  use_parallel_encoding: true
  pin_memory: true
  prefetch_factor: 2

  latent_cache_dir: data/latent_cache

  checkpoint_interval: 50

  amp: true
  compile: true

  # FIX 1: AGGRESSIVE GRADIENT CLIPPING
  grad_clip: 0.3
  grad_clip_per_param: true

  ema_decay: 0.999
  accum_steps: 4

  # FIX 2: MUCH SMALLER INVERSE LOSS WEIGHTS
  lambda_inv_enc: 0.001
  lambda_inv_dec: 0.001

  # FIX 3: CURRICULUM LEARNING
  inverse_loss_warmup_epochs: 15
  inverse_loss_max_weight: 0.05

  use_inverse_losses: true
  inverse_loss_frequency: 10

  lambda_spectral: 0.05
  lambda_relative: 0.0

  distill_micro_batch: 3
  distill_num_taus: 5

  tau_distribution:
    type: beta
    alpha: 1.2
    beta: 1.2

stages:
  operator:
    epochs: 35

    optimizer:
      name: adamw
      lr: 1.0e-3
      betas: [0.9, 0.999]
      weight_decay: 0.03

  diff_residual:
    epochs: 8
    grad_clip: 1.0
    ema_decay: 0.999

    optimizer:
      name: adamw
      lr: 5.0e-5
      weight_decay: 0.015
      betas: [0.9, 0.999]

    scheduler:
      name: cosineannealinglr
      t_max: 8
      eta_min: 3.0e-6

  consistency_distill:
    epochs: 0  # SKIP - torch.compile() CUDA graph bug

  steady_prior:
    epochs: 0

ttc:
  enabled: true
  steps: 1
  candidates: 16
  beam_width: 5
  horizon: 1
  residual_threshold: 0.35
  gamma: 1.0
  max_evaluations: 200

  sampler:
    tau_range: [0.15, 0.85]
    noise_std: 0.05
    noise_schedule: [0.08, 0.05, 0.02]

  reward:
    analytical_weight: 1.0
    grid: [64, 64]
    mass_field: rho
    energy_field: e
    momentum_field: []

    weights:
      mass: 1.0
      energy: 1.0
      penalty_negative: 0.5

    critic:
      weight: 0.0
      hidden_dim: 256
      dropout: 0.1

  decoder:
    latent_dim: 16
    query_dim: 2
    hidden_dim: 96
    mlp_hidden_dim: 128
    num_layers: 3
    num_heads: 4
    frequencies: [1.0, 2.0, 4.0, 8.0]

    output_channels:
      rho: 1
      e: 1

checkpoint:
  dir: checkpoints

evaluation:
  enabled: true
  split: test

logging:
  wandb:
    enabled: true
    project: universal-simulator
    entity: emgun-morpheus-space
    run_name: burgers-upt-operator-only
    tags: [16dim, upt, inverse-losses, fixed, operator-diffusion-only]
    group: upt-experiments
