#!/bin/bash
# Helper script to fix CUDA-contaminated cache and regenerate with CPU
# Generated by Claude Code investigation on 2025-11-18

set -euo pipefail

echo "=========================================="
echo "CUDA Cache Fix Script"
echo "=========================================="
echo ""

# Configuration
CACHE_DIR="${1:-/dev/shm/latent_cache}"
CONFIG="${2:-configs/train_burgers_upt_full_ddp_ramdisk.yaml}"

echo "Cache directory: $CACHE_DIR"
echo "Config file: $CONFIG"
echo ""

# Step 1: Check if cache exists
if [ -d "$CACHE_DIR" ]; then
    echo "✓ Found existing cache at $CACHE_DIR"

    # Count cache files
    CACHE_COUNT=$(find "$CACHE_DIR" -name "sample_*.pt" 2>/dev/null | wc -l || echo 0)
    echo "  Cache files found: $CACHE_COUNT"

    # Estimate size
    if [ $CACHE_COUNT -gt 0 ]; then
        CACHE_SIZE=$(du -sh "$CACHE_DIR" 2>/dev/null | cut -f1 || echo "unknown")
        echo "  Cache size: $CACHE_SIZE"
    fi

    echo ""
    read -p "Delete existing cache? [y/N] " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "⚠️  Deleting cache..."
        rm -rf "$CACHE_DIR"/*
        echo "✓ Cache deleted"
    else
        echo "⚠️  Keeping existing cache (may cause CUDA contamination errors)"
    fi
else
    echo "⚠️  No existing cache found at $CACHE_DIR"
    mkdir -p "$CACHE_DIR"
    echo "✓ Created cache directory"
fi

echo ""
echo "=========================================="
echo "Step 2: Regenerate Cache with CPU-only Encoding"
echo "=========================================="
echo ""

# Extract task and split from config (or use defaults)
TASK="${3:-burgers1d}"
SPLIT="${4:-train}"

echo "Task: $TASK"
echo "Split: $SPLIT"
echo "Device: CPU (forced)"
echo ""

# Run cache precomputation with CPU-only encoding
echo "Running: python scripts/precompute_latent_cache.py \\"
echo "  --config $CONFIG \\"
echo "  --tasks $TASK \\"
echo "  --splits $SPLIT \\"
echo "  --device cpu \\"
echo "  --cache-dir $CACHE_DIR"
echo ""

python scripts/precompute_latent_cache.py \
  --config "$CONFIG" \
  --tasks "$TASK" \
  --splits "$SPLIT" \
  --device cpu \
  --cache-dir "$CACHE_DIR"

echo ""
echo "=========================================="
echo "✅ Cache regeneration complete!"
echo "=========================================="
echo ""

# Verify cache
NEW_CACHE_COUNT=$(find "$CACHE_DIR" -name "sample_*.pt" 2>/dev/null | wc -l || echo 0)
NEW_CACHE_SIZE=$(du -sh "$CACHE_DIR" 2>/dev/null | cut -f1 || echo "unknown")

echo "Cache files: $NEW_CACHE_COUNT"
echo "Cache size: $NEW_CACHE_SIZE"
echo ""
echo "✓ Ready to train with multi-worker data loading!"
echo ""
echo "Next step: Launch DDP training"
echo "  python scripts/vast_launch.py launch \\"
echo "    --config $CONFIG \\"
echo "    --auto-shutdown"
